### ISSUE TITLE
Expose API service on port 80

### ISSUE THREAD

**Issue by boz** [ovrclk/akash-on-akash#2]
[Enable the API](https://docs.akash.network/guides/node/api-service) and expose it on port 80, eg

```yaml
    expose:
      - port: 1317
        as: 80
        to:
          - global: true
```
